#!/usr/bin/env bun
// @generated by sandpiper-ai-devtools@0.0.1 on 2026-03-23T15:02:31.798Z. DO NOT EDIT.
import { Command } from 'commander';
import { createRuntime, createServerProxy } from 'mcporter';
import { createCallResult } from 'mcporter';

const embeddedServer = {
  "name": "dash",
  "description": "Dash Documentation API",
  "command": {
    "kind": "stdio",
    "command": "mise",
    "args": [
      "x",
      "uv@latest",
      "--",
      "uvx",
      "--from",
      "git+https://github.com/Kapeli/dash-mcp-server.git",
      "dash-mcp-server"
    ],
    "cwd": "/Users/doug.stephen/git/sandpiper-ai/devtools/config"
  },
  "source": {
    "kind": "local",
    "path": "/Users/doug.stephen/git/sandpiper-ai/devtools/config/mcporter.json"
  },
  "sources": [
    {
      "kind": "local",
      "path": "/Users/doug.stephen/git/sandpiper-ai/devtools/config/mcporter.json"
    }
  ],
  "lifecycle": {
    "mode": "keep-alive"
  },
  "logging": {
    "daemon": {
      "enabled": true
    }
  }
} as const;
const embeddedSchemas = {
  "list_installed_docsets": {
    "type": "object",
    "properties": {},
    "title": "list_installed_docsetsArguments"
  },
  "search_documentation": {
    "type": "object",
    "properties": {
      "query": {
        "title": "Query",
        "type": "string"
      },
      "docset_identifiers": {
        "title": "Docset Identifiers",
        "type": "string"
      },
      "search_snippets": {
        "default": true,
        "title": "Search Snippets",
        "type": "boolean"
      },
      "max_results": {
        "default": 100,
        "title": "Max Results",
        "type": "integer"
      }
    },
    "required": [
      "query",
      "docset_identifiers"
    ],
    "title": "search_documentationArguments"
  },
  "enable_docset_fts": {
    "type": "object",
    "properties": {
      "identifier": {
        "title": "Identifier",
        "type": "string"
      }
    },
    "required": [
      "identifier"
    ],
    "title": "enable_docset_ftsArguments"
  },
  "load_documentation_page": {
    "type": "object",
    "properties": {
      "load_url": {
        "title": "Load Url",
        "type": "string"
      }
    },
    "required": [
      "load_url"
    ],
    "title": "load_documentation_pageArguments"
  }
} as const;
const embeddedName = "dash";
const embeddedDescription = "Dash Documentation API";
const generatorInfo = "Generated by sandpiper-ai-devtools@0.0.1 — https://github.com/steipete/mcporter";
const generatorTools = [
  {
    "name": "list-installed-docsets",
    "description": "List all installed documentation sets in Dash. An empty list is returned if the user has no docsets installed.\n    Results are automatically truncated if they would exceed 25,000 tokens.",
    "usage": "list-installed-docsets [--raw <json>]",
    "flags": "[--raw <json>]"
  },
  {
    "name": "search-documentation",
    "description": "\n    Search for documentation across docset identifiers and snippets.\n\n    Args:\n        query: The search query string\n        docset_identifiers: Comma-separated list of docset identifiers to search in (from list_installed_docsets)\n        search_snippets: Whether to include snippets in search results\n        max_results: Maximum number of results to return (1-1000)\n\n    Results are automatically truncated if they would exceed 25,000 tokens.\n    ",
    "usage": "search-documentation --query <query> --docset-identifiers <docset-identifiers> [--search-snippets <search-snippets:true|false>] [--max-results <max-results:number>] [--raw <json>]",
    "flags": "--query <query> --docset-identifiers <docset-identifiers> [--search-snippets <search-snippets:true|false>] [--max-results <max-results:number>] [--raw <json>]"
  },
  {
    "name": "enable-docset-fts",
    "description": "\n    Enable full-text search for a specific docset.\n\n    Args:\n        identifier: The docset identifier (from list_installed_docsets)\n\n    Returns:\n        True if FTS was successfully enabled, False otherwise\n    ",
    "usage": "enable-docset-fts --identifier <identifier> [--raw <json>]",
    "flags": "--identifier <identifier> [--raw <json>]"
  },
  {
    "name": "load-documentation-page",
    "description": "\n    Load a documentation page from a load_url returned by search_documentation.\n\n    Args:\n        load_url: The load_url value from a search result (must point to the local Dash API at 127.0.0.1)\n\n    Returns:\n        The documentation page content as plain text with markdown-style links\n    ",
    "usage": "load-documentation-page --load-url <load-url> [--raw <json>]",
    "flags": "--load-url <load-url> [--raw <json>]"
  }
] as const;
const embeddedMetadata = {
  "schemaVersion": 1,
  "generatedAt": "2026-03-23T15:02:31.798Z",
  "generator": {
    "name": "sandpiper-ai-devtools",
    "version": "0.0.1"
  },
  "server": {
    "name": "dash",
    "source": {
      "kind": "local",
      "path": "/Users/doug.stephen/git/sandpiper-ai/devtools/config/mcporter.json"
    },
    "definition": {
      "name": "dash",
      "description": "Dash Documentation API",
      "command": {
        "kind": "stdio",
        "command": "mise",
        "args": [
          "x",
          "uv@latest",
          "--",
          "uvx",
          "--from",
          "git+https://github.com/Kapeli/dash-mcp-server.git",
          "dash-mcp-server"
        ],
        "cwd": "/Users/doug.stephen/git/sandpiper-ai/devtools/config"
      }
    }
  },
  "artifact": {
    "path": "",
    "kind": "template"
  },
  "invocation": {
    "serverRef": "dash",
    "configPath": "/Users/doug.stephen/git/sandpiper-ai/devtools/config/mcporter.json",
    "runtime": "bun",
    "bundler": "bun",
    "timeoutMs": 30000,
    "minify": false
  }
} as const;
const artifactKind = determineArtifactKind();
const program = new Command();
program.name(embeddedName);
program.description(embeddedDescription);
program.option('-t, --timeout <ms>', 'Call timeout in milliseconds', (value) => parseInt(value, 10), 30000);
program.option('-o, --output <format>', 'Output format: text|markdown|json|raw', 'text');
const commandSignatures: Record<string, string> = {
  "list-installed-docsets": "function list_installed_docsets(): DocsetResults;",
  "search-documentation": "function search_documentation(query: string, docset_identifiers: string, search_snippets?: boolean, max_results?: number): SearchResults;",
  "enable-docset-fts": "function enable_docset_fts(identifier: string): enable_docset_ftsOutput;",
  "load-documentation-page": "function load_documentation_page(load_url: string): DocumentationPage;"
};
program.configureHelp({
	commandTerm(cmd) {
		const term = cmd.name();
		return commandSignatures[term] ?? cmd.name();
	},
});
program.showSuggestionAfterError(true);

program
	.command("list-installed-docsets")
	.summary("list-installed-docsets [--raw <json>]")
	.description("List all installed documentation sets in Dash. An empty list is returned if the user has no docsets installed.\n    Results are automatically truncated if they would exceed 25,000 tokens.")
	.usage("[--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	
	.alias("list_installed_docsets")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			
			const call = (proxy.listInstalledDocsets as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call dash.list_installed_docsets()");

program
	.command("search-documentation")
	.summary("search-documentation --query <query> --docset-identifiers <docset-identifiers> [--search-snippets <search-snippets:true|false>] [--max-results <max-results:number>] [--raw <json>]")
	.description("\n    Search for documentation across docset identifiers and snippets.\n\n    Args:\n        query: The search query string\n        docset_identifiers: Comma-separated list of docset identifiers to search in (from list_installed_docsets)\n        search_snippets: Whether to include snippets in search results\n        max_results: Maximum number of results to return (1-1000)\n\n    Results are automatically truncated if they would exceed 25,000 tokens.\n    ")
	.usage("--query <query> --docset-identifiers <docset-identifiers> [--search-snippets <search-snippets:true|false>] [--max-results <max-results:number>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--query <query>", "Set query.")
	.requiredOption("--docset-identifiers <docset-identifiers>", "Set docset_identifiers. (example: example-id)")
	.option("--search-snippets <search-snippets:true|false>", "Set search_snippets. (default: true; example: true)", (value) => value !== 'false')
	.option("--max-results <max-results:number>", "Set max_results. (default: 100; example: 100)", (value) => parseFloat(value))
	
	.alias("search_documentation")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.query !== undefined) args.query = cmdOpts.query;
		if (cmdOpts.docsetIdentifiers !== undefined) args.docset_identifiers = cmdOpts.docsetIdentifiers;
		if (cmdOpts.searchSnippets !== undefined) args.search_snippets = cmdOpts.searchSnippets;
		if (cmdOpts.maxResults !== undefined) args.max_results = cmdOpts.maxResults;
			const call = (proxy.searchDocumentation as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call dash.search_documentation(query: \"value\", docset_identifiers, ...)");

program
	.command("enable-docset-fts")
	.summary("enable-docset-fts --identifier <identifier> [--raw <json>]")
	.description("\n    Enable full-text search for a specific docset.\n\n    Args:\n        identifier: The docset identifier (from list_installed_docsets)\n\n    Returns:\n        True if FTS was successfully enabled, False otherwise\n    ")
	.usage("--identifier <identifier> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--identifier <identifier>", "Set identifier. (example: example-id)")
	
	.alias("enable_docset_fts")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.identifier !== undefined) args.identifier = cmdOpts.identifier;
			const call = (proxy.enableDocsetFts as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call dash.enable_docset_fts(identifier: \"example-id\")");

program
	.command("load-documentation-page")
	.summary("load-documentation-page --load-url <load-url> [--raw <json>]")
	.description("\n    Load a documentation page from a load_url returned by search_documentation.\n\n    Args:\n        load_url: The load_url value from a search result (must point to the local Dash API at 127.0.0.1)\n\n    Returns:\n        The documentation page content as plain text with markdown-style links\n    ")
	.usage("--load-url <load-url> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--load-url <load-url>", "Set load_url.")
	
	.alias("load_documentation_page")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.loadUrl !== undefined) args.load_url = cmdOpts.loadUrl;
			const call = (proxy.loadDocumentationPage as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call dash.load_documentation_page(load_url: \"https://example.com\")");

program
	.command('__mcporter_inspect', { hidden: true })
	.description('Internal metadata printer for mcporter inspect-cli.')
	.action(() => {
		const payload = buildMetadataPayload();
		console.log(JSON.stringify(payload, null, 2));
	});

configureToolCommandHelps();

const FORCE_COLOR = process.env.FORCE_COLOR?.toLowerCase();
const forceDisableColor = FORCE_COLOR === '0' || FORCE_COLOR === 'false';
const forceEnableColor = FORCE_COLOR === '1' || FORCE_COLOR === 'true' || FORCE_COLOR === '2' || FORCE_COLOR === '3';
const hasNoColor = process.env.NO_COLOR !== undefined;
const stdoutStream = process.stdout as NodeJS.WriteStream | undefined;
const supportsAnsiColor = !hasNoColor && (forceEnableColor || (!forceDisableColor && Boolean(stdoutStream?.isTTY)));

const tint = {
	bold(text: string): string {
		return supportsAnsiColor ? '[1m' + text + '[0m' : text;
	},
	dim(text: string): string {
		return supportsAnsiColor ? '[90m' + text + '[0m' : text;
	},
	extraDim(text: string): string {
		return supportsAnsiColor ? '[38;5;244m' + text + '[0m' : text;
	},
};

function configureGeneratedCommandHelp(command: Command): void {
	command.configureHelp({
		commandUsage(target) {
			const usage = (target.name() + ' ' + target.usage()).trim() || target.name();
			return supportsAnsiColor ? tint.bold(usage) : usage;
		},
		optionTerm(option) {
			const term = option.flags ?? '';
			return supportsAnsiColor ? tint.bold(term) : term;
		},
		optionDescription(option) {
			const description = option.description ?? '';
			return supportsAnsiColor ? tint.extraDim(description) : description;
		},
	});
}

function configureToolCommandHelps(): void {
	program.commands.forEach((cmd) => {
		if (cmd.name() === '__mcporter_inspect') {
			return;
		}
		configureGeneratedCommandHelp(cmd);
	});
}

function renderStandaloneHelp(): string {
	const colorfulTitle = tint.bold(embeddedName) + ' ' + tint.dim('— ' + embeddedDescription);
	const plainTitle = embeddedName + ' — ' + embeddedDescription;
	const title = supportsAnsiColor ? colorfulTitle : plainTitle;
	const lines = [title, '', 'Usage: ' + embeddedName + ' <command> [options]', ''];
	if (generatorTools) {
		lines.push(formatEmbeddedTools());
	}
	lines.push('', formatGlobalFlags(), '', formatQuickStart());
	if (generatorInfo) {
		lines.push('', tint.extraDim(generatorInfo));
	}
	return lines.join('\n');
}

program.helpInformation = () => renderStandaloneHelp();

function formatEmbeddedTools(): string {
	const header = supportsAnsiColor ? tint.bold('Embedded tools') : 'Embedded tools';
	if (!generatorTools.length) {
		return header;
	}
	const lines = [header];
	generatorTools.forEach((entry) => {
		const renderedDesc = entry.description
			? supportsAnsiColor
				? tint.extraDim(entry.description)
				: entry.description
			: undefined;
		const base = renderedDesc ? entry.name + ' - ' + renderedDesc : entry.name;
		lines.push('  ' + base);
		if (entry.flags) {
			const renderedFlags = supportsAnsiColor ? tint.extraDim(entry.flags) : entry.flags;
			lines.push('    ' + renderedFlags);
		}
		lines.push('');
	});
	if (lines[lines.length - 1] === '') {
		lines.pop();
	}
	return lines.join('\n');
}

function formatGlobalFlags(): string {
	const header = supportsAnsiColor ? tint.bold('Global flags') : 'Global flags';
	const entries = [
		['-t, --timeout <ms>', 'Call timeout in milliseconds'],
		['-o, --output <format>', 'text | markdown | json | raw (default text)'],
	];
	const formatted = entries.map(([flag, summary]) => '  ' + flag.padEnd(28) + summary);
	return [header, ...formatted].join('\n');
}

function formatQuickStart(): string {
  const header = supportsAnsiColor ? tint.bold('Quick start') : 'Quick start';
  const examples = quickStartExamples();
  if (!examples.length) {
    return header;
  }
  const formatted = examples.map(([cmd, note]) => '  ' + cmd + '\n    ' + tint.dim('# ' + note));
  return [header, ...formatted].join('\n');
}

function quickStartExamples(): Array<[string, string]> {
  const examples: Array<[string, string]> = [];
  const commandMap = new Map<string, string>();
  program.commands.forEach((cmd) => {
    const name = cmd.name();
    if (name !== '__mcporter_inspect') {
      commandMap.set(name, name);
    }
  });
  const embedded = Array.isArray(generatorTools) ? generatorTools : [];
  for (const entry of embedded.slice(0, 3)) {
    const commandName = commandMap.get(entry.name) ?? entry.name;
    const flags = entry.flags ? ' ' + entry.flags.replace(/<[^>]+>/g, '<value>') : '';
    examples.push([embeddedName + ' ' + commandName + flags, 'invoke ' + commandName]);
  }
  if (!examples.length) {
    examples.push([embeddedName + ' <tool> --key value', 'invoke a tool with flags']);
  }
  return examples;
}

function printResult(result: unknown, format: string) {
	const wrapped = createCallResult(result);
	switch (format) {
		case 'json': {
			const json = wrapped.json();
			if (json) {
				console.log(JSON.stringify(json, null, 2));
				return;
			}
			break;
		}
		case 'markdown': {
			const markdown = wrapped.markdown();
			if (markdown) {
				console.log(markdown);
				return;
			}
			break;
		}
		case 'raw': {
			console.log(JSON.stringify(wrapped.raw, null, 2));
			return;
		}
	}
	const text = wrapped.text();
	if (text) {
		console.log(text);
	} else {
		console.log(JSON.stringify(wrapped.raw, null, 2));
	}
}

function normalizeEmbeddedServer(server: typeof embeddedServer) {
	const base = { ...server } as Record<string, unknown>;
	if ((server.command as any).kind === 'http') {
		const urlRaw = (server.command as any).url;
		const urlValue = typeof urlRaw === 'string' ? urlRaw : String(urlRaw);
		return {
			...base,
			command: {
				...(server.command as Record<string, unknown>),
				url: new URL(urlValue),
			},
		};
	}
	if ((server.command as any).kind === 'stdio') {
		return {
			...base,
			command: {
				...(server.command as Record<string, unknown>),
				args: [ ...((server.command as any).args ?? []) ],
			},
		};
	}
	return base;
}

function determineArtifactKind(): 'template' | 'bundle' | 'binary' {
	const scriptPath = typeof process !== 'undefined' && Array.isArray(process.argv) ? process.argv[1] ?? '' : '';
	if (scriptPath.endsWith('.ts')) {
		return 'template';
	}
	if (scriptPath.endsWith('.js')) {
		return 'bundle';
	}
	return 'binary';
}

function resolveArtifactPath(): string {
	if (typeof process !== 'undefined' && Array.isArray(process.argv) && process.argv.length > 1) {
		const script = process.argv[1];
		if (script) {
			return script;
		}
	}
	return embeddedMetadata.artifact.path;
}

function buildMetadataPayload() {
	const invocation = { ...embeddedMetadata.invocation };
	const path = resolveArtifactPath();
	if (artifactKind === 'template' && path) {
		invocation.outputPath = invocation.outputPath ?? path;
	} else if (artifactKind === 'bundle' && path) {
		invocation.bundle = invocation.bundle ?? path;
	} else if (artifactKind === 'binary' && path) {
		invocation.compile = invocation.compile ?? path;
	}
	return {
		...embeddedMetadata,
		artifact: {
			path,
			kind: artifactKind,
		},
		invocation,
	};
}

async function ensureRuntime(): Promise<Awaited<ReturnType<typeof createRuntime>>> {
	return await createRuntime({
		servers: [normalizeEmbeddedServer(embeddedServer)],
	});
}

async function invokeWithTimeout<T>(call: Promise<T>, timeout: number): Promise<T> {
	if (!Number.isFinite(timeout) || timeout <= 0) {
		return await call;
	}
	let timer: ReturnType<typeof setTimeout> | undefined;
	try {
		return await Promise.race([
			call,
			new Promise<never>((_, reject) => {
				timer = setTimeout(() => {
					reject(new Error('Call timed out after ' + timeout + 'ms.'));
				}, timeout);
			}),
		]);
	} finally {
		if (timer) {
			clearTimeout(timer);
		}
	}
}

async function runCli(): Promise<void> {
	const args = process.argv.slice(2);
	if (args.length === 0) {
		program.outputHelp();
		return;
	}
	await program.parseAsync(process.argv);
}

if (process.env.MCPORTER_DISABLE_AUTORUN !== '1') {
	runCli().catch((error) => {
		const message = error instanceof Error ? error.message : String(error);
		console.error(message);
		process.exit(1);
	});
}
